# CSV to NPY

> In this file, Cr is radians.

### CSV to NPY

1. **X** (idx: 1)
2. **Y** (idx: 2)
3. Z
4. **angle** = Cr (idx: 0)
5. Joint 1
6. Joint 2
7. Joint 3
8. Joint 4
9. Joint 5
10. Joint 6
11. Joint 7
12. **manipulability** (idx: 3)

In [1]:
import csv
import numpy as np

raw = []
with open('manipulability.csv', 'r', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        x = float(row[0])
        y = float(row[1])
        Cr = float(row[3])  # radian
        m = float(row[11])
        raw.append([Cr, x, y, m])
npraw = np.array(raw)
print(npraw)
np.save('real_manip', npraw)

[[ 0.          0.1        -0.44        0.0151625 ]
 [ 0.174533    0.1        -0.44        0.0151625 ]
 [ 0.349066    0.1        -0.44        0.0151625 ]
 ...
 [ 1.0472      0.28       -0.08        0.00897977]
 [ 1.22173     0.28       -0.08        0.00897977]
 [ 1.39626     0.28       -0.08        0.00897977]]


### Load NPY

In [2]:
M = np.load('real_manip.npy')
print(M.shape)
print(M)

(893, 4)
[[ 0.          0.1        -0.44        0.0151625 ]
 [ 0.174533    0.1        -0.44        0.0151625 ]
 [ 0.349066    0.1        -0.44        0.0151625 ]
 ...
 [ 1.0472      0.28       -0.08        0.00897977]
 [ 1.22173     0.28       -0.08        0.00897977]
 [ 1.39626     0.28       -0.08        0.00897977]]
