# CSV to NPY

### Config

column index from raw file

In [1]:
import numpy as np

RAD = 1.0
DEG = np.pi / 180.

raw_file = "socialrobot_manip_2021-01-25_22-26-56.csv"
first_row_is_title = True

col_idx = {
    "tcp_X": 0,
    "tcp_Y": 1,
    "tcp_Z": 2,
    "Cr": 6,
    "pitch": 7,
    "roll": 8,
    "manip": 9
}
to_rad = {
    "Cr": DEG,
    "pitch": DEG,
    "roll": DEG,
}

### CSV to NPY

npy index:

- [0] [rad] yaw(Cr) -> gripper orientation (정수여야 filter칠 수 있음)
- [1] [rad] pitch -> gripper orientation
- [2] [rad] roll -> gripper orientation
- [3] tcp x --(transformed)-> mobile base x
- [4] tcp y --(transformed)-> mobile base y
- [5] tcp z -> target object z
- [6] manipulability

In [2]:
import csv

raw = []
with open(raw_file, 'r', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        if first_row_is_title:
            first_row_is_title = False
        else:
            tcp_X = float(row[col_idx["tcp_X"]])
            tcp_Y = float(row[col_idx["tcp_Y"]])
            tcp_Z = float(row[col_idx["tcp_Z"]])
            Cr = float(row[col_idx["Cr"]]) * to_rad["Cr"]
            pitch = float(row[col_idx["pitch"]]) * to_rad["pitch"]
            roll = float(row[col_idx["roll"]]) * to_rad["roll"]
            manip = float(row[col_idx["manip"]])
            
            if tcp_Z == 0.75:
                raw.append([Cr, tcp_X, tcp_Y, manip])
npraw = np.array(raw)
print(npraw)

[[-1.04719755  0.309      -0.3         0.06915467]
 [-0.78539816  0.309      -0.3         0.07275049]
 [-0.52359878  0.309      -0.3         0.07759805]
 ...
 [ 1.30899694  0.159       0.05        0.05844657]
 [ 1.57079633  0.159       0.05        0.06611408]
 [ 1.57079633  0.159       0.1         0.05978375]]


In [3]:
npy_name = raw_file.replace(".csv", ".npy")
np.save(npy_name, npraw)

### Load NPY

In [4]:
M = np.load(npy_name)
print(M.shape)
print(M)

(2795, 4)
[[-1.04719755  0.309      -0.3         0.06915467]
 [-0.78539816  0.309      -0.3         0.07275049]
 [-0.52359878  0.309      -0.3         0.07759805]
 ...
 [ 1.30899694  0.159       0.05        0.05844657]
 [ 1.57079633  0.159       0.05        0.06611408]
 [ 1.57079633  0.159       0.1         0.05978375]]
